version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory_management
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - networkInventoryManagement

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - networkInventoryManagement

volumes:
  postgres-data:
networks:
  networkInventoryManagement: 
    driver:
      bridge